import os
import urllib.request
import json
import xml.etree.ElementTree as ET
from datetime import datetime
import email.utils

def get_gag():
    api_key = os.environ.get("GEMINI_API_KEY", "THISISDUMMYKEY")
    if api_key == "THISISDUMMYKEY":
        print("Warning: Using dummy API key. Falling back to dummy gag.")
        return "ダミーのギャグ：布団が吹っ飛んだ！"
    
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={api_key}"
    headers = {
        "Content-Type": "application/json"
    }
    data = {
        "contents": [{
            "parts": [{
                "text": "今日の面白いオヤジギャグを1つ日本語で作成してください。出力はギャグのテキストだけにし、余計な説明や導入、挨拶などは一切含めないでください。"
            }]
        }]
    }
    req = urllib.request.Request(url, data=json.dumps(data).encode("utf-8"), headers=headers, method="POST")
    try:
        with urllib.request.urlopen(req) as response:
            res_data = json.loads(response.read().decode("utf-8"))
            # Extract text from response
            gag = res_data["candidates"][0]["content"]["parts"][0]["text"].strip()
            return gag
    except Exception as e:
        print(f"Error fetching gag from Gemini API: {e}")
        print("Falling back to dummy gag.")
        return "ダミーのギャグ：アルミ缶の上にあるみかん！"

def update_rss(gag):
    rss_file = "rss3.xml"
    
    if not os.path.exists(rss_file):
        print(f"Error: {rss_file} not found.")
        return

    tree = ET.parse(rss_file)
    root = tree.getroot()
    channel = root.find("channel")
    if channel is None:
        print("Error: <channel> element not found in RSS.")
        return

    now = datetime.now()
    pub_date_str = email.utils.formatdate(localtime=True)
    
    # Update lastBuildDate
    last_build_date = channel.find("lastBuildDate")
    if last_build_date is not None:
        last_build_date.text = pub_date_str
    else:
        last_build_date = ET.SubElement(channel, "lastBuildDate")
        last_build_date.text = pub_date_str
    
    # Check and update title / description if they are defaults
    title_el = channel.find("title")
    if title_el is not None and title_el.text == "AI News Filter":
        title_el.text = "今日のギャグフィード"
    
    desc_el = channel.find("description")
    if desc_el is not None and desc_el.text == "Filtered AI news feed generated by GitHub Actions":
        desc_el.text = "Google Gemini APIによって毎日自動生成される今日のギャグフィードです。"

    # Create new item
    item = ET.Element("item")
    
    title = ET.SubElement(item, "title")
    title.text = f"今日のギャグ ({now.strftime('%Y-%m-%d')})"
    
    link = ET.SubElement(item, "link")
    link_el = channel.find("link")
    link.text = link_el.text if link_el is not None else "https://github.com/"
    
    guid = ET.SubElement(item, "guid")
    guid.set("isPermaLink", "false")
    guid.text = f"gag-{now.strftime('%Y%m%d')}"
    
    pub_date = ET.SubElement(item, "pubDate")
    pub_date.text = pub_date_str
    
    category = ET.SubElement(item, "category")
    category.text = "ギャグ"
    
    description = ET.SubElement(item, "description")
    description.text = gag

    # Insert at the beginning of items list
    first_item_idx = -1
    for idx, child in enumerate(channel):
        if child.tag == "item":
            first_item_idx = idx
            break
            
    if first_item_idx != -1:
        channel.insert(first_item_idx, item)
    else:
        channel.append(item)

    # Limit to 15 items
    items = channel.findall("item")
    if len(items) > 15:
        for extra_item in items[15:]:
            channel.remove(extra_item)

    # Format XML nicely
    try:
        ET.indent(tree, space="  ")
    except AttributeError:
        pass

    # Write back to rss.xml
    tree.write(rss_file, encoding="utf-8", xml_declaration=True)
    print(f"Successfully updated {rss_file} with new gag: {gag}")

if __name__ == "__main__":
    gag = get_gag()
    update_rss(gag)
